app/blueprint/blog/models.py
from app import db, login_manager
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True)
    username = db.Column(db.String(50), unique=True)
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    password = db.Column(db.String(200))

    def hash_my_password(self, password):
        self.password = generate_password_hash(password)

    def check_my_password(self, password):
        return check_password_hash(self.password, password)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key = True) 
    title = db.Column(db.String(250), nullable = False)   
    body = db.Column(db.String(250), nullable = False)
    make = db.Column(db.String(250), nullable = False) 
    model = db.Column(db.String(250), nullable = False)    
    color = db.Column(db.String(250), nullable = False)
    year = db.Column(db.Integer, nullable = False)    
    price = db.Column(db.Float, nullable = False) 
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user = db.relationship('User', backref='post')
    #back ref reference from previous class
    #name of model, name of table working in
    
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)
    
class Car(db.Model):
    id = db.Column(db.Integer, primary_key = True) 
    name = db.Column(db.String(250), nullable = False) 
    make = db.Column(db.String(250), nullable = False) 
    model = db.Column(db.String(250), nullable = False)    
    color = db.Column(db.String(250), nullable = False)  
    year = db.Column(db.Integer, nullable = False)   
    price = db.Column(db.Float, nullable = False)
    owner_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    

app/__init__.py
from flask import Flask, flash, redirect, url_for
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

def create_app():
    app = Flask(__name__)

    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    # from app import routes, models
    from app.blueprint.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.blueprint.blog import bp as blog_bp
    app.register_blueprint(blog_bp)

    from app.blueprint.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    login_manager.login_view = 'auth.login'
    login_manager.login_message = 'You are not allowed to access this page'
    login_manager.login_message_category = 'danger'
    
    return app

app/blueprint/blog/__init__.py
from flask import Blueprint

bp = Blueprint('blog', __name__, url_prefix='/blog')

from . import routes, models

app/blueprint/blog/routes.py
from . import bp as app
from app import db
from flask import render_template, request, redirect, url_for, flash
from app.blueprint.blog.models import Post
from flask_login import current_user, login_required

@app.route('/posts')
@login_required
def posts():
    all_posts = Post.query.all()
    return render_template('posts.html', posts=all_posts)

#create a route that allows us to get a single post based on its id 

@app.route('/post/<id>')
@login_required
def post_by_id(id):
    post = Post.query.get(int(id))
    return render_template('post_single.html', post=post)

@app.route('/create_post', methods=["POST"])
@login_required
def create_post():
    title = request.form['inputTitle']
    body = request.form['inputBody']
    make = request.form['inputMake']
    model = request.form['inputModel']
    year = request.form['inputYear']
    color = request.form['inputColor']
    price = request.form['inputPrice']
    new_post = Post(title = title, body = body, make = make, model = model, year = year, color = color, price = price, user_id=current_user.id)
    db.session.add(new_post)
    db.session.commit()
    flash('Car post created successfully', 'success')
    return redirect(url_for('blog.posts')) 

app/blueprint/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix='/')

from . import routes, models

app/blueprint/main/routes.py
from . import bp as app 
from flask import render_template
from flask_login import current_user

@app.route('/')
def home():
    return render_template('home.html', user=current_user)

@app.route('/about')
def about():
    return render_template('about.html')

@app.route('/contact')
def contact():
    return render_template('contact.html')

app/routes.py
from . import bp as app
from app import db
from flask import render_template, request, redirect, url_for, flash
from app.blueprint.blog.models import Post
from flask_login import current_user, login_required

@app.route('/posts')
@login_required
def posts():
    all_posts = Post.query.all()
    return render_template('posts.html', posts=all_posts)

#create a route that allows us to get a single post based on its id 

@app.route('/post/<id>')
@login_required
def post_by_id(id):
    post = Post.query.get(int(id))
    return render_template('post_single.html', post=post)

@app.route('/create_post', methods=["POST"])
@login_required
def create_post():
    title = request.form['inputTitle']
    body = request.form['inputBody']
    make = request.form['inputMake']
    model = request.form['inputModel']
    year = request.form['inputYear']
    color = request.form['inputColor']
    price = request.form['inputPrice']
    new_post = Post(title = title, body = body, make = make, model = model, year = year, color = color, price = price, user_id=current_user.id)
    db.session.add(new_post)
    db.session.commit()
    flash('Post created successfully', 'success')
    return redirect(url_for('blog.posts')) 

app/templates/about.html
{% extends './layout.html' %}


{% block title %}About{% endblock title %}


{% block content %}
<h1>About</h1>
<p>This is the about page</p>
{% endblock content %}

app/templates/contact.html
{% extends './layout.html' %}


{% block title %}Contact{% endblock title %}


{% block content %}
<h1>Contact</h1>
<p>This is the contact page</p>
{% endblock content %}

app/templates/home.html
{% extends './layout.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<h1>Home</h1>
{% if user.is_authenticated %}
    <p>Welcome to our app {{ user.username }}</p>
{% else %}
    <p>Please <a href="{{ url_for('auth.login') }}">login</a></p>
{% endif %}
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} | Fakebook</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark mb-5">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Fakebook</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.contact') }}">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('blog.posts') }}">Posts</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        {% if current_user.is_anonymous %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.reset_password') }}">Reset Password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="flashes">
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
        {% block content %}{% endblock content %}
    </main>
    <footer>
        This is a footer
    </footer>
</body>
</html>

app/templates/login.html
{% extends './layout.html' %}

{% block title %}Login{% endblock title %}

{% block content %}
<h1>Login</h1>
<form action="{{ url_for('auth.login') }}" method="POST">
    <input type="hidden" name="next" value="{{ request.args.get('next', '') }}">
    <div class="mb-3">
        <label for="email" class="form-label">Email address</label>
        <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

app/templates/post_single.html
{% extends './layout.html' %}

{% block title %}{{post.title}}{% endblock title %}

{% block content %}
<h1>{{post.title}}</h1>
<p>{{post.body}}</p>
<p>{{post.make}}</p>
<p>{{post.model}}</p>
<p>{{post.year}}</p>
<p>{{post.color}}</p>
<p>{{post.price}}</p>
{% endblock content %}

app/templates/posts.html
{% extends './layout.html' %}
{% block title %}Posts{% endblock title %}

{% block content %}
<h1>Posts</h1>
<form action="{{ url_for('blog.create_post') }}" method="POST">
    <div class="mb-3">
        <label for="inputTitle" class="form-label">Title</label>
        <input type="text" class="form-control" id="inputTitle" name="inputTitle">
    </div>
    <div class="mb-3">
        <label for="inputBody" class="form-label">Body</label>
        <input type="text" class="form-control" id="inputBody" name="inputBody">
    </div>
    <div class="mb-3">
        <label for="inputMake" class="form-label">Make</label>
        <input type="text" class="form-control" id="inputMake" name="inputMake">
    </div>
    <div class="mb-3">
        <label for="inputModel" class="form-label">Model</label>
        <input type="text" class="form-control" id="inputModel" name="inputModel">
    </div>
    <div class="mb-3">
        <label for="inputYear" class="form-label">Year</label>
        <input type="text" class="form-control" id="inputYear" name="inputYear">
    </div>
    <div class="mb-3">
        <label for="inputColor" class="form-label">Color</label>
        <input type="text" class="form-control" id="inputColor" name="inputColor">
    </div>
    <div class="mb-3">
        <label for="inputPrice" class="form-label">Price</label>
        <input type="text" class="form-control" id="inputPrice" name="inputPrice">
    </div>   
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% for post in posts %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title"><a href="{{ url_for('blog.post_by_id', id=post.id) }}">{{ post.title }}</a></h5>
            {{post.body}}
            {{post.make}}
            {{post.model}}
            {{post.year}}
            {{post.color}}
            {{post.price}}
        </div>
        <div class="card-footer">
            This post brought to you by: {{ post.user.first_name }} {{ post.user.last_name }}
        </div>
    </div>
{% endfor %}
{% endblock content %}

app/templates/register.html
{% extends './layout.html' %}

{% block title %}Register{% endblock title %}

{% block content %}
<h1>Register</h1>
<form action="{{ url_for('auth.register') }}" method="POST">
    <div class="mb-3">
        <label for="email" class="form-label">Email address</label>
        <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password">
    </div>
    <div class="mb-3">
        <label for="confirmPassword" class="form-label">Confirm Password</label>
        <input type="password" class="form-control" id="confirmPassword" name="confirmPassword">
    </div>
    <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" id="username" name="username">
    </div>
    <div class="mb-3">
        <label for="firstName" class="form-label">First Name</label>
        <input type="text" class="form-control" id="firstName" name="firstName">
    </div>
    <div class="mb-3">
        <label for="lastName" class="form-label">Last Name</label>
        <input type="text" class="form-control" id="lastName" name="lastName">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

app/templates/reset-password.html
{% extends './layout.html' %}

{% block title %}Reset Password{% endblock title %}

{% block content %}
<h1>Reset Password</h1>
<form action="{{ url_for('auth.reset_password') }}" method="POST">
    <div class="mb-3">
        <label for="oldPassword" class="form-label">Old Password</label>
        <input type="password" class="form-control" id="oldPassword" name="oldPassword">
    </div>
    <div class="mb-3">
        <label for="confirmOldPassword" class="form-label">Confirm Old Password</label>
        <input type="password" class="form-control" id="confirmOldPassword" name="confirmOldPassword">
    </div>
    <div class="mb-3">
        <label for="newPassword" class="form-label">New Password</label>
        <input type="password" class="form-control" id="newPassword" name="newPassword">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}